In [78]:
import random
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


df = pd.read_csv('/Users/leonardo/Desktop/dsml_lab/Lab5/train_dataset.csv')

y = df['target']
X = df.drop(columns=['target'])

In [79]:
cols = len(X.columns)
for row in X.index:
    if (X.iloc[row,:].isna().sum())/cols >= 0.5:
        print(row)

# nothing to drop

In [80]:
X.head()

,cont_0,cont_1,cont_2,cont_3,cont_4,cont_5,cont_6,cont_7,cont_8,cont_9,...,ord_18,ord_19,cat_0,cat_1,cat_2,cat_3,cat_4,cat_5,cat_6,cat_7
0,-0.029933,19.494106,-4.330267,NaN,-6.403516,-12.474620,NaN,-0.180768,440.930299,NaN,...,NaN,ord_7_val_5,cat_0_val_9,cat_1_val_2,cat_2_val_1,cat_3_val_10,cat_4_val_0,cat_5_val_0,cat_6_val_0,cat_7_val_1
1,0.004747,1.930336,2.370512,0.014357,-2.381447,2.545120,-652.050389,NaN,NaN,NaN,...,ord_7_val_2,ord_7_val_4,cat_0_val_2,cat_1_val_1,NaN,cat_3_val_9,NaN,cat_5_val_0,cat_6_val_0,cat_7_val_5
2,NaN,18.865632,1.826231,-0.033690,-7.177250,8.423474,-3322.816093,6.550298,-137.358945,NaN,...,ord_7_val_2,ord_7_val_4,cat_0_val_6,cat_1_val_3,NaN,NaN,cat_4_val_0,cat_5_val_0,cat_6_val_0,cat_7_val_1
3,-0.017541,NaN,9.851084,0.035294,1.077285,4.897107,-647.925452,-2.024097,NaN,11.097455,...,NaN,ord_7_val_4,cat_0_val_2,NaN,cat_2_val_2,cat_3_val_18,NaN,NaN,cat_6_val_0,cat_7_val_5
4,0.005074,-32.895531,-12.880423,0.025106,NaN,1.029729,-3938.124133,NaN,172.214384,9.974146,...,ord_7_val_2,ord_7_val_1,cat_0_val_3,cat_1_val_0,cat_2_val_0,cat_3_val_13,NaN,cat_5_val_0,cat_6_val_0,cat_7_val_3

In [81]:
# Separate continous, ordinal and categorical attributes

X_cont= X.loc[:,"cont_0":"cont_29"]
X_ord = X.loc[:, "ord_0":"ord_19"]
X_cat = X.loc[:,"cat_0":"cat_7"]

In [82]:
#for col in X_cont.columns:
#    X_cont.fillna(np.mean(X_cont[col]), inplace=True)

#for col in X_ord.columns:
#   X_ord.fillna(-1, inplace = True)

#for col in X_cat.columns:
   # X_cat.fillna('missing', inplace=True)

In [83]:
from sklearn.preprocessing import StandardScaler

zscore_s = StandardScaler()
X_cont_norm = pd.DataFrame(zscore_s.fit_transform(X_cont), columns=X_cont.columns)

for col in X_cont_norm.columns:
    print(col, str(np.mean(X_cont_norm[col])), ' ' , str(np.std(X_cont_norm[col])))

# fillna with the mean (0)

X_cont_norm.fillna(0, inplace=True)

cont_0 1.894087367957616e-17   1.0
cont_1 2.172027926717241e-18   1.0
cont_2 7.284976267631515e-17   1.0
cont_3 3.704602376225757e-18   1.0
cont_4 -2.9452548632543013e-18   1.0
cont_5 -1.7778383713763974e-17   1.0
cont_6 -3.1681187927918196e-17   1.0000000000000002
cont_7 -3.0963680122353403e-17   1.0
cont_8 -1.176151848971819e-17   1.0000000000000002
cont_9 1.5929790217770755e-17   1.0
cont_10 -2.0603973282190147e-17   1.0
cont_11 -8.850438892589996e-18   1.0
cont_12 -5.1563333509441234e-17   1.0
cont_13 -8.922679812809965e-18   1.0
cont_14 1.253551941461364e-17   1.0
cont_15 1.4118711545118075e-17   0.9999999999999999
cont_16 4.47726991657278e-18   1.0
cont_17 3.9081325233795465e-17   1.0
cont_18 1.1130148679393858e-16   1.0
cont_19 2.1694819264100765e-17   1.0
cont_20 1.9152095303506745e-17   1.0
cont_21 -2.07501007522766e-17   1.0
cont_22 -2.386874610993408e-17   1.0
cont_23 -5.959679058587547e-17   0.9999999999999999
cont_24 -9.107654016613262e-18   1.0
cont_25 -2.532863599899707e-17   1.0
cont_26 -2.0771765087996247e-17   1.0
cont_27 9.24607973870628e-18   1.0
cont_28 -1.1896906417079953e-17   0.9999999999999999
cont_29 1.772295329270672e-17   1.0

In [84]:
X_cont_norm.head()

,cont_0,cont_1,cont_2,cont_3,cont_4,cont_5,cont_6,cont_7,cont_8,cont_9,...,cont_20,cont_21,cont_22,cont_23,cont_24,cont_25,cont_26,cont_27,cont_28,cont_29
0,-1.147122,0.340294,-0.052171,0.000000,-0.841283,-1.498153,0.000000,-0.587915,1.440385,0.000000,...,0.000000,0.000000,-1.073369,0.021483,-2.133477,0.317710,-0.510826,0.000000,0.000000,0.512830
1,0.065070,-0.106847,0.661753,-0.107335,-0.387511,0.482247,0.373006,0.000000,0.000000,0.000000,...,0.928893,0.000000,-0.346947,-0.794180,-0.851676,0.000000,0.000000,0.000000,0.162483,0.117195
2,0.000000,0.324294,0.603764,-0.947736,-0.928576,1.257327,-0.513239,1.152110,-0.782648,0.000000,...,0.335883,-1.207260,0.535069,-0.003379,-0.727475,0.528439,0.181328,-0.341161,0.522381,0.634336
3,-0.713981,0.000000,1.458759,0.258885,0.002706,0.792364,0.374375,-1.064428,0.000000,0.729891,...,-0.097876,-0.211556,0.000000,-0.363976,-0.238890,0.591151,0.000000,0.951319,0.270899,0.352329
4,0.076516,-0.993449,-0.963134,0.080691,0.000000,0.282438,-0.717418,0.000000,0.407399,0.652549,...,-1.444920,1.432525,1.500660,1.487117,1.266513,0.000000,0.595388,-1.060751,-1.071612,-0.901202

In [85]:
X_cont_norm.isna().sum()

cont_0     0
cont_1     0
cont_2     0
cont_3     0
cont_4     0
cont_5     0
cont_6     0
cont_7     0
cont_8     0
cont_9     0
cont_10    0
cont_11    0
cont_12    0
cont_13    0
cont_14    0
cont_15    0
cont_16    0
cont_17    0
cont_18    0
cont_19    0
cont_20    0
cont_21    0
cont_22    0
cont_23    0
cont_24    0
cont_25    0
cont_26    0
cont_27    0
cont_28    0
cont_29    0
dtype: int64

In [86]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()
X_ord_oe = pd.DataFrame(oe.fit_transform(X_ord), columns=X_ord.columns)

#for i in X_ord.columns:
#    print(X_ord[i].unique())
X_ord_oe.fillna(-1, inplace=True)
X_ord_oe.head()

,ord_0,ord_1,ord_2,ord_3,ord_4,ord_5,ord_6,ord_7,ord_8,ord_9,ord_10,ord_11,ord_12,ord_13,ord_14,ord_15,ord_16,ord_17,ord_18,ord_19
0,1.0,0.0,0.0,6.0,1.0,4.0,1.0,2.0,-1.0,0.0,3.0,2.0,0.0,3.0,4.0,0.0,1.0,7.0,-1.0,5.0
1,2.0,1.0,-1.0,4.0,1.0,4.0,-1.0,1.0,-1.0,-1.0,3.0,1.0,2.0,2.0,2.0,2.0,1.0,-1.0,2.0,4.0
2,-1.0,1.0,1.0,-1.0,2.0,-1.0,-1.0,2.0,0.0,0.0,4.0,1.0,1.0,3.0,-1.0,-1.0,-1.0,2.0,2.0,4.0
3,1.0,1.0,1.0,-1.0,2.0,-1.0,2.0,-1.0,-1.0,-1.0,3.0,3.0,1.0,2.0,3.0,2.0,0.0,4.0,-1.0,4.0
4,4.0,-1.0,1.0,-1.0,2.0,1.0,-1.0,1.0,1.0,-1.0,1.0,2.0,1.0,3.0,3.0,1.0,2.0,4.0,2.0,1.0

In [92]:
# Drop categorical columns with only one category plus NaN

for i in X_cat.columns:
    num = len((X_cat[i].unique()))
    if num <= 2:
        X_cat.drop(columns={i}, inplace=True)

X_cat.fillna('missing', inplace=True)

In [94]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False, dtype=int)
X_cat_ohe = pd.DataFrame(ohe.fit_transform(X_cat))

In [95]:
X_cat_ohe.head()

,0,1,2,3,4,5,6,7,8,9,...,42,43,44,45,46,47,48,49,50,51
0,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,1,0,1,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0