In [2]:
import random
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


df = pd.read_csv('/Users/leonardo/Desktop/dsml_lab/Lab5/train_dataset.csv')

y = df['target']
X = df.drop(columns=['target'])

In [3]:
cols = len(X.columns)
for row in X.index:
    if (X.iloc[row,:].isna().sum())/cols >= 0.5:
        print(row)

# nothing to drop

In [4]:
X.head()

,cont_0,cont_1,cont_2,cont_3,cont_4,cont_5,cont_6,cont_7,cont_8,cont_9,...,ord_18,ord_19,cat_0,cat_1,cat_2,cat_3,cat_4,cat_5,cat_6,cat_7
0,-0.029933,19.494106,-4.330267,NaN,-6.403516,-12.474620,NaN,-0.180768,440.930299,NaN,...,NaN,ord_7_val_5,cat_0_val_9,cat_1_val_2,cat_2_val_1,cat_3_val_10,cat_4_val_0,cat_5_val_0,cat_6_val_0,cat_7_val_1
1,0.004747,1.930336,2.370512,0.014357,-2.381447,2.545120,-652.050389,NaN,NaN,NaN,...,ord_7_val_2,ord_7_val_4,cat_0_val_2,cat_1_val_1,NaN,cat_3_val_9,NaN,cat_5_val_0,cat_6_val_0,cat_7_val_5
2,NaN,18.865632,1.826231,-0.033690,-7.177250,8.423474,-3322.816093,6.550298,-137.358945,NaN,...,ord_7_val_2,ord_7_val_4,cat_0_val_6,cat_1_val_3,NaN,NaN,cat_4_val_0,cat_5_val_0,cat_6_val_0,cat_7_val_1
3,-0.017541,NaN,9.851084,0.035294,1.077285,4.897107,-647.925452,-2.024097,NaN,11.097455,...,NaN,ord_7_val_4,cat_0_val_2,NaN,cat_2_val_2,cat_3_val_18,NaN,NaN,cat_6_val_0,cat_7_val_5
4,0.005074,-32.895531,-12.880423,0.025106,NaN,1.029729,-3938.124133,NaN,172.214384,9.974146,...,ord_7_val_2,ord_7_val_1,cat_0_val_3,cat_1_val_0,cat_2_val_0,cat_3_val_13,NaN,cat_5_val_0,cat_6_val_0,cat_7_val_3

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

#print(X_train.head())
#print(X_test.head())

In [6]:
# Separate continous, ordinal and categorical attributes both for test and train

X_train_cont= X_train.loc[:,"cont_0":"cont_29"]
X_train_ord = X_train.loc[:, "ord_0":"ord_19"]
X_train_cat = X_train.loc[:,"cat_0":"cat_7"]

X_test_cont = X_test.loc[:,"cont_0":"cont_29"]
X_test_ord = X_test.loc[:, "ord_0":"ord_19"]
X_test_cat = X_test.loc[:,"cat_0":"cat_7"]

In [7]:
from sklearn.preprocessing import StandardScaler

zscore_s = StandardScaler()
X_train_cont_norm = pd.DataFrame(zscore_s.fit_transform(X_train_cont), columns=X_train_cont.columns)
X_test_cont_norm = pd.DataFrame(zscore_s.transform(X_test_cont), columns=X_test_cont.columns)


for col in X_train_cont_norm.columns:
    print(col, str(np.mean(X_train_cont_norm[col])), ' ' , str(np.std(X_train_cont_norm[col])))

# fillna with the mean (0)

X_train_cont_norm.fillna(0, inplace=True)
X_test_cont_norm.fillna(0, inplace=True)

cont_0 -2.4802524984644658e-17   1.0
cont_1 -5.751830025041286e-18   1.0
cont_2 2.952393638892383e-17   0.9999999999999999
cont_3 2.7540416114732565e-17   1.0
cont_4 1.9509685221309725e-17   1.0
cont_5 1.1901888371190958e-17   0.9999999999999999
cont_6 1.1855551764629036e-17   1.0
cont_7 -9.357022442086155e-18   1.0
cont_8 -4.482764070588541e-17   1.0
cont_9 7.95235294639172e-18   1.0
cont_10 -1.4696829890239247e-17   0.9999999999999999
cont_11 -1.3866181071426544e-17   1.0
cont_12 2.021388576614218e-17   1.0
cont_13 3.571563597788831e-17   1.0
cont_14 -1.3800774556938684e-17   1.0
cont_15 9.932104218061228e-18   1.0
cont_16 1.4956695251756248e-18   1.0
cont_17 -5.414221455639445e-17   0.9999999999999999
cont_18 3.58558150930244e-17   0.9999999999999999
cont_19 4.12990525686893e-17   1.0
cont_20 -9.447659644455625e-17   0.9999999999999999
cont_21 -1.8792193735303317e-17   1.0
cont_22 9.485885314391444e-18   1.0
cont_23 3.9717313346008955e-18   0.9999999999999999
cont_24 -4.0813450358211444e-17   1.0
cont_25 2.1747273492935733e-17   1.0
cont_26 3.431152835486135e-17   1.0
cont_27 2.0191469480291174e-17   1.0
cont_28 3.0789523075989807e-17   0.9999999999999999
cont_29 1.2109277285839214e-17   1.0

In [8]:
X_train_cont_norm.head()

,cont_0,cont_1,cont_2,cont_3,cont_4,cont_5,cont_6,cont_7,cont_8,cont_9,...,cont_20,cont_21,cont_22,cont_23,cont_24,cont_25,cont_26,cont_27,cont_28,cont_29
0,1.509352,0.169376,-1.450631,-0.560276,1.035362,0.000000,-0.981909,-0.737829,-0.926231,-0.702504,...,-0.648584,0.874928,0.068098,0.113402,0.399115,-0.618630,-0.561777,-0.718868,-0.759563,-0.452497
1,1.909156,1.454257,-0.409751,-2.036806,1.165372,-1.631259,0.000000,1.684924,0.000000,0.246894,...,0.000000,-0.461849,1.660317,0.528206,0.000000,-0.565677,1.187785,0.000000,0.000000,0.000000
2,0.000000,1.098347,0.000000,-0.483876,-0.019371,1.108814,0.625430,-0.480647,0.000000,0.779372,...,0.000000,-0.504865,0.000000,-1.133698,-0.611920,-0.472263,0.377864,0.087689,0.000000,0.236001
3,-0.815210,0.794348,-0.640569,0.675160,-1.923465,-0.083021,0.227720,0.000000,-1.288494,0.396484,...,0.640146,-2.074462,-1.069100,1.244504,0.364991,1.489779,1.201467,0.640083,0.000000,1.536403
4,0.000000,0.166291,1.208258,1.155114,0.034094,0.000000,-0.671694,-0.924599,0.250105,1.530114,...,-1.127745,0.863240,-0.393485,0.000000,0.551386,0.000000,0.815892,2.030143,0.721459,0.820184

In [9]:
X_train_cont_norm.isna().sum()

cont_0     0
cont_1     0
cont_2     0
cont_3     0
cont_4     0
cont_5     0
cont_6     0
cont_7     0
cont_8     0
cont_9     0
cont_10    0
cont_11    0
cont_12    0
cont_13    0
cont_14    0
cont_15    0
cont_16    0
cont_17    0
cont_18    0
cont_19    0
cont_20    0
cont_21    0
cont_22    0
cont_23    0
cont_24    0
cont_25    0
cont_26    0
cont_27    0
cont_28    0
cont_29    0
dtype: int64

In [10]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()
X_train_ord_oe = pd.DataFrame(oe.fit_transform(X_train_ord), columns=X_train_ord.columns)
X_test_ord_oe = pd.DataFrame(oe.transform(X_test_ord), columns=X_test_ord.columns)

#for i in X_ord.columns:
#    print(X_ord[i].unique())
X_train_ord_oe.fillna(-1, inplace=True)
X_test_ord_oe.fillna(-1, inplace=True)

X_train_ord_oe.head()

,ord_0,ord_1,ord_2,ord_3,ord_4,ord_5,ord_6,ord_7,ord_8,ord_9,ord_10,ord_11,ord_12,ord_13,ord_14,ord_15,ord_16,ord_17,ord_18,ord_19
0,3.0,-1.0,0.0,7.0,2.0,2.0,3.0,1.0,1.0,1.0,3.0,1.0,1.0,4.0,3.0,-1.0,-1.0,5.0,-1.0,3.0
1,5.0,-1.0,3.0,7.0,2.0,1.0,0.0,0.0,0.0,0.0,-1.0,-1.0,-1.0,-1.0,0.0,3.0,2.0,2.0,2.0,-1.0
2,-1.0,-1.0,2.0,6.0,0.0,-1.0,-1.0,0.0,1.0,0.0,-1.0,1.0,3.0,1.0,1.0,1.0,2.0,4.0,4.0,1.0
3,1.0,1.0,-1.0,-1.0,1.0,8.0,2.0,2.0,0.0,-1.0,-1.0,1.0,3.0,2.0,4.0,1.0,-1.0,1.0,4.0,3.0
4,0.0,-1.0,1.0,3.0,2.0,1.0,2.0,3.0,1.0,-1.0,2.0,2.0,0.0,1.0,3.0,1.0,0.0,2.0,3.0,5.0

In [11]:
# Drop categorical columns with only one category plus NaN

for i in X_train_cat.columns:
    num = len((X_train_cat[i].unique()))
    if num <= 2:
        X_train_cat.drop(columns={i}, inplace=True)

for i in X_test_cat.columns:
    num = len((X_test_cat[i].unique()))
    if num <= 2:
        X_test_cat.drop(columns={i}, inplace=True)

X_train_cat.fillna('missing', inplace=True)
X_test_cat.fillna('missing', inplace=True)

In [12]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False, dtype=int)
X_train_cat_ohe = pd.DataFrame(ohe.fit_transform(X_train_cat))
X_test_cat_ohe = pd.DataFrame(ohe.transform(X_test_cat))

In [13]:
X_train_cat_ohe.head()

,0,1,2,3,4,5,6,7,8,9,...,42,43,44,45,46,47,48,49,50,51
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,1

In [14]:
X_train_new = np.hstack((X_train_cont_norm, X_train_ord_oe, X_train_cat_ohe))
X_test_new = np.hstack((X_test_cont_norm, X_test_ord_oe, X_test_cat_ohe))

In [15]:
pd.DataFrame(X_train_new).head()

,0,1,2,3,4,5,6,7,8,9,...,92,93,94,95,96,97,98,99,100,101
0,1.509352,0.169376,-1.450631,-0.560276,1.035362,0.000000,-0.981909,-0.737829,-0.926231,-0.702504,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,1.909156,1.454257,-0.409751,-2.036806,1.165372,-1.631259,0.000000,1.684924,0.000000,0.246894,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.000000,1.098347,0.000000,-0.483876,-0.019371,1.108814,0.625430,-0.480647,0.000000,0.779372,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-0.815210,0.794348,-0.640569,0.675160,-1.923465,-0.083021,0.227720,0.000000,-1.288494,0.396484,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.000000,0.166291,1.208258,1.155114,0.034094,0.000000,-0.671694,-0.924599,0.250105,1.530114,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [1]:
pd.DataFrame(X_test_new).isna().sum()

NameError: name 'pd' is not defined

In [ ]:
'''from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(X_train_new, y_train)
y_test_pred = reg.predict(X_test_new)'''

'from sklearn.linear_model import LinearRegression\n\nreg = LinearRegression()\nreg.fit(X_train_new, y_train)\ny_test_pred = reg.predict(X_test_new)'

:

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures

reg = make_pipeline(PolynomialFeatures(5), LinearRegression())
reg.fit(X_train_new, y_train)
y_test_pred = reg.predict(X_test_new)

In [ ]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
# Compute R2, MAE and MSE:
r2 = r2_score(y_test, y_test_pred)
mae = mean_absolute_error(y_test, y_test_pred)
mse = mean_squared_error(y_test, y_test_pred)

print('r2 metric: ', r2)
print('mae metric: ', mae)
print('mse metrice: ', mse)

r2 metric:  0.3097022580680139
mae metric:  0.6369996190834106
mse metrice:  0.6766147021917046

In [ ]:
from sklearn.linear_model import Ridge
reg2 = Ridge(alpha=0.5)
reg2.fit(X_train_new, y_train)
y_test_pred2 = reg2.predict(X_test_new)

In [ ]:
from sklearn.model_selection import cross_val_score
r2 = cross_val_score(reg2, X_test_new, y_test, cv=5, scoring='r2')

print(r2)

[0.31753931 0.31841761 0.244558   0.22113391 0.18894233]